name: Deploy (Production)
on:
  push:
    branches: [main]
jobs:
  checks:
    uses: lorenzogm/lorenzogm/.github/workflows/checks.yml@main
  deploy:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          vercel-args: '--prod' # Optional
